version: "2"

linters:
  default: all
  disable:
    - depguard
    - dogsled
    - godot
    - mnd
    - noinlineerr
    - nolintlint
    - wsl # deprecated

  settings:
    cyclop:
      max-complexity: 15
    funlen:
      lines: -1
    lll:
      line-length: 150
    varnamelen:
      ignore-names:
        - tt
        - i
        - eg
    wrapcheck:
      ignore-sigs:
        - (*golang.org/x/sync/errgroup.Group).Wait(
        - (*golang.org/x/sync/semaphore.Weighted).Acquire(
        - (context.Context).Err(

  exclusions:
    rules:
      - linters:
          - containedctx
          - gochecknoglobals
        path: _test\.go

formatters:
  enable:
    - gci
    - gofumpt
